### ISSUE TITLE
Xacro file argument introspection

### ISSUE THREAD

**Issue by reinzor** [ros/xacro#345]
We would like to add a feature that allows a user to introspect xacro files. This way, we can query what arguments are available and prompt these to the user. We could also add additional validation to the defined arguments and some documentation. What are your thoughts about this? An example:

```xml
<xacro:arg name="argument1" default="value1" doc="Argument 1 doc" choices="value1, value2, value3" />
```

```bash
xacro --args test.xacro
```

```
arguments:
  - name: argument 1
  - default: value1
  - choices: [value1, value2, value3]
  - doc: Argument 1 doc
```
